PrismaFacMovil/Models/Factura.cs
namespace PrismaFacMovil.Models
{
    public class Factura
    {
		public int IdFactura { get; set; }

		public int? IdCliente { get; set; }

		public int? IdEmisor { get; set; }

		public string? NumeroFactura { get; set; }

		public string? NumeroAutorizacion { get; set; }

		public DateTime? FechaAutorizacion { get; set; }

		public string? TotalDescuento { get; set; }

		public decimal? Subtotal { get; set; }

		public decimal? ValorIva { get; set; }
		public string Estado { get; set; }
		public decimal? Total { get; set; }
		public string? NombreCliente { get; set; }
		public string? ApellidoCliente { get; set; }
		public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; }
    }
}

PrismaFacMovil/Models/Producto.cs
namespace PrismaFacMovil.Models
{
    public class Producto
    {
        public int IdProducto { get; set; }
        public int? IdEmisor { get; set; }
        public string Nemonico { get; set; }
        public string Descripcion { get; set; }
        public decimal? PorcentajeDescuento { get; set; }
        public bool? Estado { get; set; }
        public int? Stok { get; set; }
        public decimal? PrecioUnitario { get; set; }
        
    }
}

PrismaFacMovil/Controllers/FacturaController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PrismaFacMovil.Models;
using PrismaFacMovil.Servicios;

namespace PrismaFacMovil.Controllers
{
    public class FacturaController : Controller
    {
        private readonly IFacturaApi facturaApi;

        public FacturaController(IFacturaApi facturaApi)
        {
            this.facturaApi = facturaApi;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Producto()
        {
            return View();
        }
        public IActionResult FacturaAprobada()
        {
            return View();
        }
        public IActionResult FacturasEmitidas()
        {
            return View();
        }
        public IActionResult Resumen()
        {
            FacturaViewcs dtoFacturaView = new FacturaViewcs();
            List<Factura> lstFactura = new List<Factura>();
            Factura dtoFactura = new Factura();
            List<ProductoFactura> lstProducto = new List<ProductoFactura>();
            Cliente dtoCliente = new Cliente();
            dtoFactura = JsonConvert.DeserializeObject<Factura>(HttpContext.Session.GetString("dtoFactura"));
            lstFactura.Add(dtoFactura);
            lstProducto = JsonConvert.DeserializeObject<List<ProductoFactura>>(HttpContext.Session.GetString("lstProducto"));
            dtoCliente = JsonConvert.DeserializeObject<Cliente>(HttpContext.Session.GetString("dtoCliente"));
            dtoCliente.InicialNombre = dtoCliente.Nombre1.FirstOrDefault();
            dtoCliente.InicialApellido = dtoCliente.Apellido1.FirstOrDefault();
            dtoFacturaView.lstProductoFactura = lstProducto;
            dtoFacturaView.lstFactura = lstFactura;
            dtoFacturaView.dtoCliente = dtoCliente;
            return View(dtoFacturaView);
        }

        [HttpGet]
        public async Task<IActionResult> Lista(int intIdEmisor)
        {

            Cliente dtoCliente = new Cliente();
            intIdEmisor = Convert.ToInt32(HttpContext.Session.GetInt32("varIdEmisor"));


            List<Cliente> lstCliente = await facturaApi.Lista(intIdEmisor);


            return View("Index", lstCliente);

        }

        [HttpPost]
        public async Task<JsonResult> ObtenerIdentificacion(string strIdentificacion)
        {

            List<Cliente> lstCliente = new List<Cliente>();
            string strNombre = "0";
            string strApellido = "0";
            if (string.IsNullOrEmpty(strIdentificacion))
            {
                strIdentificacion = "0";
            }

            Cliente dtoCliente = new Cliente();
            dtoCliente = await facturaApi.ObtenerIdentificacion(strIdentificacion);

            return new JsonResult(Ok(dtoCliente));


        }

        [HttpPost]
        public async Task<IActionResult> Guardar(Cliente Cliente)
        {


            string strVMCliente = JsonConvert.SerializeObject(Cliente);
            HttpContext.Session.SetString("dtoCliente", strVMCliente);
            return new JsonResult(Ok());



        }
        [HttpGet]
        public async Task<IActionResult> ListaProducto(int intIdEmisor)
        {

            Producto dtoProducto = new Producto();
            intIdEmisor = Convert.ToInt32(HttpContext.Session.GetInt32("varIdEmisor"));
            List<Producto> lstProductoResult = new List<Producto>();

            List<Producto> lstProducto = await facturaApi.ListaProducto(intIdEmisor);

            foreach (Producto dtoProductoFor in lstProducto)
            {
                if (dtoProductoFor.Estado == false)
                {
                    lstProductoResult.Add(dtoProductoFor);
                }
            }
            Cliente dtoCliente = new Cliente();
            FacturaViewcs dtoFacturaView = new FacturaViewcs();
            
            dtoCliente = JsonConvert.DeserializeObject<Cliente>(HttpContext.Session.GetString("dtoCliente"));
            dtoFacturaView.lstProducto = lstProductoResult;
            dtoFacturaView.dtoCliente = dtoCliente;
            return View("Producto", dtoFacturaView);

        }
        [HttpPost]
        public async Task<JsonResult> ObtenerNemonicoDescripcion(string strDescripcion)
        {
            string strNemonico = "";
            List<Producto> lstProductoResult = new List<Producto>();
            if (string.IsNullOrEmpty(strNemonico))
            {
                strNemonico = "0";
            }
            if (string.IsNullOrEmpty(strDescripcion))
            {
                strDescripcion = "0";
            }

            Producto ModeloProducto = new Producto();
            List<Producto> lstProducto = await facturaApi.ObtenerNemonicoDescripcion(strNemonico, strDescripcion);
            //foreach(Producto dtoProducto in lstProducto)
            //{
            //    if (dtoProducto.Estado == false) { 
                    
            //    }

            //}
            return new JsonResult(Ok(lstProducto));


        }

        [HttpPost]
        public async Task<IActionResult> GuardarProducto(Factura Factura, List<DetalleFactura> DetalleFactura, List<ProductoFactura> lstProducto)
        {


            string strVMFactura = JsonConvert.SerializeObject(Factura);
            HttpContext.Session.SetString("dtoFactura", strVMFactura);


            string strListaProducto = JsonConvert.SerializeObject(lstProducto);
            HttpContext.Session.SetString("lstProducto", strListaProducto);

            List<DetalleFactura> lstDetalleFactura = new List<DetalleFactura>();
            string strListaDetalleFactura = JsonConvert.SerializeObject(DetalleFactura);
            HttpContext.Session.SetString("lstDetalleFactura", strListaDetalleFactura);
            lstDetalleFactura = JsonConvert.DeserializeObject<List<DetalleFactura>>(HttpContext.Session.GetString("lstDetalleFactura"));
            return new JsonResult(Ok());

        }
        /// <summary>
        /// Controlador para enviar datos para emisión de factura
        /// 2023/10/22 JG: Quito variables de aplica iva para manejarlo centralizado en el API.
        /// </summary>
        /// <returns>Respuesta Correcto: 1 Error 0</returns>
        public async Task<IActionResult> GenerarFactura()
        {
            GenerarFactura dtoGenerarFactura = new GenerarFactura();
            Establecimiento dtoEstablecimiento = new Establecimiento();
            Sucursal dtoSucursal = new Sucursal();
            Emisor dtoEmisor = new Emisor();
            List<DetalleFactura> lstDetalleFactura = new List<DetalleFactura>();
            Cliente dtoCliente = new Cliente();
            lstDetalleFactura = JsonConvert.DeserializeObject<List<DetalleFactura>>(HttpContext.Session.GetString("lstDetalleFactura"));
            dtoCliente = JsonConvert.DeserializeObject<Cliente>(HttpContext.Session.GetString("dtoCliente"));
            dtoCliente.IdEmisor = HttpContext.Session.GetInt32("varIdEmisor");
            dtoEmisor.IdEmisor = (int)HttpContext.Session.GetInt32("varIdEmisor");
            dtoEstablecimiento.IdEstablecimiento = (int)HttpContext.Session.GetInt32("varIdEstablecimiento");
            dtoSucursal.IdSucursal = (int)HttpContext.Session.GetInt32("varIdSucursal");
            dtoEstablecimiento.CodigoEstablecimiento = HttpContext.Session.GetString("varCodigoEstablecimiento");
            dtoSucursal.CodigoSucursal = HttpContext.Session.GetString("varCodigoSucursal");
            dtoGenerarFactura.dtoClientes = dtoCliente;
            dtoGenerarFactura.dtoEmisor = dtoEmisor;
            dtoGenerarFactura.dtoEstablecimiento = dtoEstablecimiento;
            dtoGenerarFactura.dtoSucursal = dtoSucursal;
            dtoGenerarFactura.lstDetalleFactura = lstDetalleFactura;
            GenerarFactura dtoGenerarFacturaRespuesta = new GenerarFactura();

            dtoGenerarFacturaRespuesta = await facturaApi.Guardar(dtoGenerarFactura);

            HttpContext.Session.SetString("MensajeFactura", dtoGenerarFacturaRespuesta.Mensaje);
            HttpContext.Session.SetInt32("CodigoFactura", dtoGenerarFacturaRespuesta.Codigo);
            return View("FacturaAprobada", dtoGenerarFactura);



        }
        [HttpGet]
		public async Task<ActionResult> ConsultaFactura()
		{

			List<Factura> lstFactura = await facturaApi.Lista();
			HttpContext.Session.SetString("CodigoFactura", String.Empty);
			HttpContext.Session.SetString("MensajeErrorLogin", string.Empty);


			return View("FacturasEmitidas", lstFactura);

		}
        [HttpPost]
		public async Task<IActionResult> ConsultaProducto(int IdFactura)
		{

			Producto ModeloProducto = new Producto();

            List<Producto> lstProducto = await facturaApi.ConsultaProducto(IdFactura);


            if (lstProducto.Count == 0)
            {
                return new JsonResult(Ok(ModeloProducto));
            }
            return new JsonResult(Ok(lstProducto));
           

		}
   
		public async Task<IActionResult> ObtenerFacturas(IFormCollection frmColeccion)
		{
			string strFechaInicio = frmColeccion["ConsultaDesde"];
			string strFechaFin = frmColeccion["ConsultaHasta"];


			List<Factura> lstFactura = await facturaApi.ConsultaFecha(strFechaInicio, strFechaFin);
			return View("FacturasEmitidas", lstFactura);

		}
	}
}

PrismaFacMovil/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;
using PrismaFacMovil.Servicios;
using PrismaFacMovil.Models;
using PrismaFacMovil.Servicios;

namespace PrismaFacMovil.Controllers
{
    public class ProductoController : Controller
    {
        private readonly IProductoApi productoApi;
        public ProductoController(IProductoApi productoApi)
        { 
            this.productoApi = productoApi;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Nuevo()
        {
            return View();
        }
        public IActionResult Editar()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Lista(int IdEmisor)
        {
            Producto dtoProducto = new Producto();
            IdEmisor = Convert.ToInt32(HttpContext.Session.GetInt32("varIdEmisor"));
            List<Producto> lstProducto = await productoApi.Lista(IdEmisor);


            return View("Index", lstProducto);

        }
        [HttpGet]
        public async Task<IActionResult> ObtenerProducto(int IdProducto)
        {
            Producto dtoProducto = new Producto();
            List<Producto> lstProducto = new List<Producto>();
            dtoProducto = await productoApi.Obtener(IdProducto);
            lstProducto.Add(dtoProducto);
            return View("Editar", lstProducto);
        }
        [HttpPost]
        public async Task<IActionResult> GuardarCambios(IFormCollection frmProducto)
        {
            Producto dtoProducto = new Producto();
            ProductoResult dtoProductoResult = new ProductoResult();
            if (!string.IsNullOrEmpty(frmProducto["IdProducto"].ToString()))
            {
                dtoProducto.IdProducto = Convert.ToInt32(frmProducto["IdProducto"].ToString());
            }

            dtoProducto.Descripcion = frmProducto["Descripcion"].ToString();
            dtoProducto.Stok = Convert.ToInt32(frmProducto["Cantidad"].ToString());
            dtoProducto.PrecioUnitario = Convert.ToDecimal(frmProducto["Precio"].ToString());
            dtoProducto.PorcentajeDescuento = Convert.ToDecimal(frmProducto["Descuento"].ToString());
            dtoProducto.IdEmisor = HttpContext.Session.GetInt32("varIdEmisor");

            dtoProductoResult = await productoApi.Guardar(dtoProducto);
            if (dtoProductoResult.Codigo == "1")
            {
                HttpContext.Session.SetString("CodigoExistenteProducto", dtoProductoResult.Codigo);
                HttpContext.Session.SetString("MensajeExistenteProducto", dtoProductoResult.Mensaje);
                return RedirectToAction("Lista", "Producto");
            }
            else if (dtoProductoResult.Codigo == "0")
            {
                HttpContext.Session.SetInt32("CodigoExistenteProducto", 2);
                HttpContext.Session.SetString("MensajeExistenteProducto", dtoProductoResult.Mensaje);
                return RedirectToAction("Lista", "Producto");
            }
            else
            {
                return RedirectToAction("Lista", "Producto");
            }


        }

        public async Task<IActionResult> ObtenerNemonicoDescripcion(IFormCollection frmColeccion)
        {
            string strNemonico = frmColeccion["Nemonico"];
            string strDescripcion = frmColeccion["Descripcion"];
            if (string.IsNullOrEmpty(strNemonico))
            {
                strNemonico = "0";
            }
            if (string.IsNullOrEmpty(strDescripcion))
            {
                strDescripcion = "0";
            }

            Producto ModeloProducto = new Producto();
            List<Producto> lstProducto = await productoApi.ObtenerNemonicoDescripcion(strNemonico, strDescripcion);

            return View("Index", lstProducto);


        }
    }
}

PrismaFacMovil/Views/Factura/FacturaAprobada.cshtml
@model GenerarFactura
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor objAccesor
@{
	ViewData["Title"] = "Nuevo Producto";
	Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>BrookWood</title>
	<link rel="icon" href="assets/images/favicon/icon.png">
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800;900&amp;display=swap"
		  rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&amp;display=swap"
		  rel="stylesheet">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<script src="https://kit.fontawesome.com/41bcea2ae3.js" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
	<link rel="stylesheet" href="~/css/all.min.css">
	<link rel="stylesheet" href="~/css/slick.css">
	<link rel="stylesheet" href="~/css/bootstrap.min.css">
	<link rel="stylesheet" href="~/css/style.css">
	<link rel="stylesheet" href="~/css/media-query.css">
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
		<symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
			<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
		</symbol>
		<symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
			<path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z" />
		</symbol>
		<symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
			<path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
		</symbol>
	</svg>
</head>
<body>
	<div class="site_content">
		<!-- Preloader Start -->
		
		<!-- Preloader End -->
		<!-- Payment Success Section Start -->
		@if (Model.Codigo == 1)
		{
			<section id="payment-success-first">
				<div class="payment-success-second-wrapper">
					<div class="container">
						<div class="payment-success-second">
							<div class="container">
								<div class="payment-success-second-wrap">
									<h1 class="success-title">Felicitaciones</h1>
									<div class="success-img mt-24">
										<img src="/images/success/success.png" alt="success-img">
									</div>
									<h2 class="success-subtitle mt-24">@Model.dtoFactura.NumeroAutorizacion</h2>
									<p class="success-para">Revisa la factura emitida en la opción consulta de facturas</p>
								</div>
							</div>
						</div>
						<div class="track-cancel mt-32">
							<a href="track-order.html">Ir a inicio</a>
						</div>
					</div>
				</div>
			</section>

		}
		else
		{
			<section id="payment-success-first">
				<div class="payment-success-second-wrapper">
					<div class="container">
						<div class="payment-success-second">
							<div class="container">
								<div class="payment-success-second-wrap">
									<h1 class="success-title">Error!</h1>
									<div class="success-img mt-24">
										<img src="/images/success/success.png" alt="success-img">
									</div>
									<h2 class="success-subtitle mt-24">Lo sentimos</h2>
									<p class="success-para">No podemos emitir la factura, vuelve a intentarlo</p>
								</div>
							</div>
						</div>
						<div class="track-cancel mt-32">
							<a asp-controller="Registro" asp-action="Ingreso">Ir a inicio</a>
						</div>
					</div>
				</div>
			</section>
		}

		<!-- Payment Success Section End -->
	</div>
	<script src="~/js/jquery-min-3.6.0.js"></script>
	<script src="~/js/slick.min.js"></script>
	<script src="~/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/custom.js"></script>
</body>
</html>

PrismaFacMovil/Views/Factura/FacturaNegada.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

PrismaFacMovil/Views/Factura/FacturasEmitidas.cshtml
@model List<Factura>
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor objAccesor;
@{
	ViewData["Title"] = "FacturasEmitidas Page";
	Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>BrookWood</title>
	<link rel="icon" href="assets/images/favicon/icon.png">
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800;900&amp;display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&amp;display=swap" rel="stylesheet">
	<link rel="stylesheet" href="~/css/all.min.css">
	<link rel="stylesheet" href="~/css/slick.css">
	<link rel="stylesheet" href="~/css/bootstrap.min.css">
	<link rel="stylesheet" href="~/css/style.css">
	<link rel="stylesheet" href="~/css/media-query.css">
</head>
<body>
	<div class="site_content">
		<!-- Preloader Start -->
		<div class="loader-mask">
			<div class="loader">
				<div></div>
				<div></div>
			</div>
		</div>
		<!-- Preloader End -->
		<!-- Header Section Start -->
		<header id="top-navbar" class="top-navbar">
			<div class="container">
				<div class="top-navbar_full">
					<div class="back-btn d-flex align-items-center">
						<a asp-controller="Registro" asp-action="Ingreso"><img src="/images/forget-password-screen/back-btn.svg" alt="back-btn-img"></a>
					</div>
					<div class="top-navbar-title d-flex align-items-center">
						<p>FAQs</p>
					</div>
				</div>
			</div>
			<div class="navbar-boder"></div>
		</header>
		<!-- Header Section End -->
		<!-- Faq Details Section Start -->
		<section id="faq-sec">
			<div class="container">
				<div class="faq-full-sec mt-24">
					<h1 class="d-none">Faq Page</h1>
					<div class="accordion custom-acc" id="accordionPanelsStayOpenExample">
						@foreach(var item in Model){
							
							<div class="accordion-item border-0 mt-24">
							<h6 class="accordion-header">
								<div class="row">
										@if (item.Estado == "NO AUTORIZADO")
										{
											<div class="col-1"><input type="checkbox" class="form-check-input Fecha"></div>
										}
										else
										{
											<div class="col-1"><input type="checkbox" class="form-check-input Fecha" checked></div>
										}
									
									<div class="col">
										<button class="accordion-button custom_icon collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#acordion_@item.IdFactura">
											<span style="font-size: 12px;">Factura: @item.NumeroFactura</span> <span style="font-size: 14px;">Total: @item.Total</span>
										</button>
									</div>
								</div>

							</h6>
								<div id="acordion_@item.IdFactura" class="accordion-collapse collapse">
								<div class="accordion-body faq-answer">
									<div class="text-center">
										<h6 class="small" style="font-size: 10px;">#@item.NumeroAutorizacion </h6>
									</div>
									<br />
									<div class="check-page-bottom mt-12">
										<div class="check-page-bottom-deatails">
											<div class="col">
												<p>Cliente:</p>
											</div>
											<div class="col">
												<p>@item.ApellidoCliente @item.NombreCliente </p>
											</div>
										</div>
										<div class="check-page-bottom-deatails mt-12">
											<div class="col">
												<p>Fecha: </p>
											</div>
											<div class="col">
												<p>@item.FechaAutorizacion</p>
											</div>
										</div>
										<div class="check-page-bottom-deatails mt-12">
											<div class="col">
												<p style="color: #16128a;">Descuento: </p>
											</div>
											<div class="col">
												<p class="" style="color: #16128a;">@item.TotalDescuento $</p>
											</div>
										</div>
										<div class="check-page-bottom-deatails mt-12">
											<div class="col">
												<p>SubTotal:</p>
											</div>
											<div class="col">
												<p class=""> @item.Subtotal $</p>
											</div>
										</div>

										<div class="check-page-bottom-deatails mt-12">
											<div class="col">
												<p class="" style="color: #ED0006;">Iva:</p>
											</div>
											<div class="col">
												<p class="" style="color: #ED0006;"> @item.ValorIva $</p>
											</div>
										</div>
										<div class="checkoutpage-boder mt-12"></div>
										<div class="check-page-bottom-deatails mt-12">
											<div class="col">
													<p class="col-black">Total:</p>
											</div>
											<div class="col">
												<p class="col-black" > @item.Total $</p>
											</div>
										</div>

									</div>
									<br />
										<a class="forget-btn producto"  name="@item.IdFactura" style="color: #25D366;">Detalles de factura</a>
								</div>
							</div>
							<div class="faq-bottom-border"></div>

						</div>
						}
					</div>
				</div>
			</div>
			<div class="review-btn">
				<a id="BuscarFacturas">Buscar facturas</a>
			</div>
		</section>
		<!-- Faq Details Section End -->
	</div>
	<div class="modal fade" id="ModalProducto" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="staticBackdropLabel">Detalle factura</h5>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
					<div id="ProductoView">
						
					</div>
					
				</div>
			</div>
		</div>
	</div>
<form id="FrmBuscarFactura" asp-action="ObtenerFacturas" asp-controller="Factura" method="post" class="row g-3 needs-validation">
	<div class="offcanvas offcanvas-bottom addtohome-popup theme-offcanvas" tabindex="-1" id="offcanvas" aria-modal="true" role="dialog" data-bs-backdrop="static" data-bs-keyboard="false">
		<button type="button" class="btn-close text-reset popup-close-home" data-bs-dismiss="offcanvas" aria-label="Close"></button>
		<div class="offcanvas-body small">
			<div class="partner-page-content-full text-center">
				<h4 class="offcial-title-part-page">Buscar por:</h4>

			</div>
			
				<div class="row border bg-light rounded">
					<div class="col ">
						<h6>Desde</h6>
						<input type="datetime-local" id="ConsultaDesde"
							   name="ConsultaDesde" value="2023-06-12" />
					</div>
					<div class="col ">
						<h6>Hasta</h6>
						<input type="datetime-local" id="ConsultaHasta"
							   name="ConsultaHasta" value="2023-06-12" />
					</div>
				</div>

			
			
			<div class="form-sec mt-16">
				<button class="btn-emisor btn" type="submit" >Buscar</button>
			</div>

		</div>
	</div>
</form>
	<script src="~/js/jquery-min-3.6.0.js"></script>
	<script src="~/js/slick.min.js"></script>
	<script src="~/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/custom.js"></script>
	<script src="~/js/FacturasEmitidas.js"></script>
</body>
</html>